### ISSUE TITLE
您好作者，我看您开源的项目中支持了mid360，可是我跑mid360数据集的的时候显示校验不正确

### ISSUE THREAD

**Issue by wangdebin00223** [gloryhry/fast_lio_sam#1]
[ERROR] [1733879672.336811825]: Client [/laserMapping] wants topic /livox/lidar to have datatype/md5sum [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181], but our version has [livox_ros_driver2/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6]. Dropping connection.

我想请教您是如何使用mid360 运行该算法的

**Comment by gloryhry** [comment]
你需要在雷达的驱动里将雷达的输出格式改为sensor_msgs::PointCloud2

**Comment by wangdebin00223** [comment]
> 你需要在雷达的驱动里将雷达的输出格式改为sensor_msgs::PointCloud2

好的，明白了，感谢！！
还想请教一下，您后续有对于这个代码加入赋色吗？采用什么思路呢？好像直接将点云投影到坐标系会导致赋色有时不是很准确..

**Comment by gloryhry** [comment]
是相机的颜色赋到雷达上吗？这个包里面没有这个功能。你可以参考一下fast-livo这个算法

**Comment by wangdebin00223** [comment]
> 是相机的颜色赋到雷达上吗？这个包里面没有这个功能。你可以参考一下fast-livo这个算法

好的 谢谢
